config/routes.rb
UAssingnment::Application.routes.draw do
  get "education/index"
  get "hotel/index"
  get "construction/index"
  get "mobile/index"
  get "category/index"
  get "category/show"
  post "/education/player"
  get "/education/player"
  get "/construction/player"
 post "/construction/player"
 get "/hotel/player"
 post "/hotel/player"
  get "/mobile/player"
 post "/mobile/player"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'category#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/construction.rb
class Construction < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/education.rb
class Education < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/mobile.rb
class Mobile < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
  @categories = Category.all
  end
 
  def show
  	category = Category.find(params[:id]).category_name
  	model_name = category.capitalize!
  	@images = "#{model_name}.all"
  end
  private
  def category_params
  	params.require(:category).permit(:id, :name)
  end
end

app/controllers/construction_controller.rb
class ConstructionController < ApplicationController
  def index
  	@construction = Construction.all
  end

  def player
  	p params[:image]
  	img = params[:image]
  	@images = img.split(",")
  	render :partial => "player", :object => @images
    end

end

app/controllers/education_controller.rb
class EducationController < ApplicationController
  def index
  	@education = Education.all
  end

  def new
  end

  def player
  	p "------------------------------------"
  	p params[:image]
  	img = params[:image]
  	@images = img.split(",")
  	p "------------------------------"
  	p @images
  	p "-----------------------------"
  	render :partial => "player", :object => @images
    end


  	
     
  
end

app/controllers/hotel_controller.rb
class HotelController < ApplicationController
  def index
  	@hotels = Hotel.all
  end

  def player
  	p params[:image]
  	img = params[:image]
  	@images = img.split(",")
  	render :partial => "player", :object => @images
    end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  def index
  	@mobile = Mobile.all
  end
  def player
  	p params[:image]
  	img = params[:image]
  	@images = img.split(",")
  	render :partial => "player", :object => @images
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/construction_helper.rb
module ConstructionHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/views/category/index.html.erb
<h1>Select one category form the list below</h1>

<p><h3><%= link_to "Mobile", mobile_index_path %></h3></p>
<p><h3><%= link_to "Education", education_index_path%></h3></p>
<p><h3><%= link_to "Construction", construction_index_path%></h3></p>
<p><h3><%= link_to "Hotel", hotel_index_path%></h3></p>

app/views/construction/_player.html.erb
<h1>Player</h1>

<ul id="image_player" style="display: none;">
  <% @images.each do |image|%>  
  <li><img src="<%= image %>"></li>
  <% end %>
</ul>
  

<script>
  $(function() {
    var options = {
      stageWidth:400,
      stageHeight:300,
      autoStart:false,
      pauseOnHover:true,
      delay:1,
      loop:true
    };
    $('#image_player').imagePlayer(options);
  });
  </script>

app/views/construction/index.html.erb
<div id = "replaced">
<div id="container">
	<form name="frm_images"  method="post" action="">
		<div>
			<input type="hidden" value="" name="hdn_images" id="hdn_images">		
		</div>
	</form>
	<input type="button" name="btn_submit" onclick="submit()" value="send">
	<%#= link_to "Madhu", "/education/player", :onclick=>"submit()"%>
	<% @construction.each do |construction|%>
	<div class="single_image">	
		
		 <%= image_tag construction.image.url, :width => 100, :height => 150, :crop => :fill %>
		<input type="checkbox" class="images" name="images[]" id="<%=construction.id%>"  value="<%=construction.image.url%>">
	</div>
	<% end %>
</div>
</div>

<div id = "hi">

</div>

<script type="text/javascript">
		
	function submit()
	{
		var chkId = '';
		$('.images:checked').each(function() {
		  chkId += $(this).val() + ",";
		});
		chkId = chkId.slice(0,-1);// Remove last comma 	
		

		$.ajax({
			url:"/construction/player?image="+chkId,
			type: "POST",
			context: document.body
			}).done(function(data) {
						 $('#replaced').html(data);
			});
		
	}	

	 

</script>

app/views/education/_player.html.erb
<h1>Player</h1>

<ul id="image_player" style="display: none;">
  <% @images.each do |image|%>  
  <li><img src="<%= image %>"></li>
  <% end %>
</ul>
  

<script>
  $(function() {
    var options = {
      stageWidth:400,
      stageHeight:300,
      autoStart:false,
      pauseOnHover:true,
      delay:1,
      loop:true
    };
    $('#image_player').imagePlayer(options);
  });
  </script>

app/views/education/index.html.erb
<div id = "replaced">
<div id="container">
	<form name="frm_images"  method="post" action="">
		<div>
			<input type="hidden" value="" name="hdn_images" id="hdn_images">		
		</div>
	</form>
	<input type="button" name="btn_submit" onclick="submit()" value="send">
	<%#= link_to "Madhu", "/education/player", :onclick=>"submit()"%>
	<% @education.each do |education|%>
	<div class="single_image">	
		
		 <%= image_tag education.image.url, :width => 100, :height => 150, :crop => :fill%>
		<input type="checkbox" class="images" name="images[]" id="<%=education.id%>"  value="<%=education.image.url%>">
	</div>
	<% end %>
</div>
</div>

<div id = "hi">

</div>

<script type="text/javascript">
	
	// $( "input[type=checkbox]" ).on( "click", images(this.value) )
	
	
  // $(function() {
  //   var options = {
  //     stageWidth:400,
  //     stageHeight:300,
  //     autoStart:false,
  //     pauseOnHover:true,
  //     delay:1,
  //     loop:true
  //   };
  //   $('#container').imagePlayer(options);
  // });
	
	function submit()
	{
		var chkId = '';
		$('.images:checked').each(function() {
		  chkId += $(this).val() + ",";
		});
		chkId = chkId.slice(0,-1);// Remove last comma 	
		

		$.ajax({
			url:"/education/player?image="+chkId,
			type: "POST",
			context: document.body
			}).done(function(data) {
				//do somthing
		
                    $('#replaced').html(data);

				// $('#replaced').html(data);
			});
		//$("#hdn_images").val(chkId);
		//document.frm_images.submit();	
	
	}	

	 

</script>

app/views/hotel/_player.html.erb
<h1>Player</h1>

<ul id="image_player" style="display: none;">
  <% @images.each do |image|%>  
  <li><img src="<%= image %>"></li>
  <% end %>
</ul>
  

<script>
  $(function() {
    var options = {
      stageWidth:400,
      stageHeight:300,
      autoStart:false,
      pauseOnHover:true,
      delay:1,
      loop:true
    };
    $('#image_player').imagePlayer(options);
  });
  </script>

app/views/hotel/index.html.erb
<div id = "replaced">
<div id="container">
	<form name="frm_images"  method="post" action="">
		<div>
			<input type="hidden" value="" name="hdn_images" id="hdn_images">		
		</div>
	</form>
	<input type="button" name="btn_submit" onclick="submit()" value="send">
	<%#= link_to "Madhu", "/education/player", :onclick=>"submit()"%>
	<% @hotels.each do |hotel| %>
	<div class="single_image">	
		
		 <%= image_tag hotel.image.url, :width => 100, :height => 150, :crop => :fill %>
		<input type="checkbox" class="images" name="images[]" id="<%=hotel.id%>"  value="<%=hotel.image.url%>">
	</div>
	<% end %>
</div>
</div>

<div id = "hi">

</div>

<script type="text/javascript">
		
	function submit()
	{
		var chkId = '';
		$('.images:checked').each(function() {
		  chkId += $(this).val() + ",";
		});
		chkId = chkId.slice(0,-1);// Remove last comma 	
		

		$.ajax({
			url:"/hotel/player?image="+chkId,
			type: "POST",
			context: document.body
			}).done(function(data) {
						 $('#replaced').html(data);
			});
		
	}	

	 

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UAssingnment</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mobile/_player.html.erb
<h1>Player</h1>

<ul id="image_player" style="display: none;">
  <% @images.each do |image|%>  
  <li><img src="<%= image %>"></li>
  <% end %>
</ul>
  

<script>
  $(function() {
    var options = {
      stageWidth:400,
      stageHeight:300,
      autoStart:false,
      pauseOnHover:true,
      delay:1,
      loop:true
    };
    $('#image_player').imagePlayer(options);
  });
  </script>

app/views/mobile/index.html.erb
<div id = "replaced">
<div id="container">
  <form name="frm_images"  method="post" action="">
    <div>
      <input type="hidden" value="" name="hdn_images" id="hdn_images">    
    </div>
  </form>
  <input type="button" name="btn_submit" onclick="submit()" value="send">
  <%#= link_to "Madhu", "/education/player", :onclick=>"submit()"%>
  <% @mobile.each do |mobile| %>
  <div class="single_image">  
    
     <%= image_tag mobile.image.url, :width => 100, :height => 150, :crop => :fill %>
    <input type="checkbox" class="images" name="images[]" id="<%=mobile.id%>"  value="<%=mobile.image.url%>">
  </div>
  <% end %>
</div>
</div>

<div id = "hi">

</div>

<script type="text/javascript">
    
  function submit()
  {
    var chkId = '';
    $('.images:checked').each(function() {
      chkId += $(this).val() + ",";
    });
    chkId = chkId.slice(0,-1);// Remove last comma  
    

    $.ajax({
      url:"/mobile/player?image="+chkId,
      type: "POST",
      context: document.body
      }).done(function(data) {
             $('#replaced').html(data);
      });
    
  } 

   

</script>